apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  finalizers:
  - cluster.cluster.x-k8s.io
  - kommander.mesosphere.io/capicluster-kommandercluster
  generation: 3
  annotations:
    caren.nutanix.com/cluster-uuid: 0194a4bd-4983-7623-bf2c-2848deacb7db
  labels:
    cluster.x-k8s.io/provider: nutanix
    konvoy.d2iq.io/cluster-name: cluster-2
    konvoy.d2iq.io/provider: nutanix
    cluster.x-k8s.io/cluster-name: cluster-2
    infraId: ntnx-45k7g
    topology.cluster.x-k8s.io/owned: ""
  name: cluster-2
  namespace: nav-workspace-8rnws
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    services:
      cidrBlocks:
      - 10.96.0.0/12
  controlPlaneEndpoint:
    host: 10.38.1.17
    port: 6443
  topology:
    class: nkp-nutanix
    controlPlane:
      metadata: {}
      replicas: 1
    variables:
    - name: clusterConfig
      value:
        addons:
          ccm:
            credentials:
              secretRef:
                name: cluster-2-pc-credentials
            strategy: HelmAddon
          clusterAutoscaler:
            strategy: HelmAddon
          cni:
            provider: Cilium
            strategy: HelmAddon
          csi:
            defaultStorage:
              provider: nutanix
              storageClassConfig: volume
            providers:
              nutanix:
                credentials:
                  secretRef:
                    name: cluster-2-pc-credentials-for-csi
                storageClassConfigs:
                  volume:
                    allowExpansion: true
                    parameters:
                      csi.storage.k8s.io/fstype: ext4
                      description: CSI StorageClass nutanix-volume for cluster-2
                      flashMode: DISABLED
                      hypervisorAttached: ENABLED
                      storageContainer: default
                      storageType: NutanixVolumes
                    reclaimPolicy: Delete
                strategy: HelmAddon
            snapshotController:
              strategy: HelmAddon
          nfd:
            strategy: HelmAddon
          serviceLoadBalancer:
            configuration:
              addressRanges:
              - end: 10.38.1.20
                start: 10.38.1.18
            provider: MetalLB
        controlPlane:
          nutanix:
            machineDetails:
              bootType: uefi
              cluster:
                name: PHX-SPOC001-1
                type: name
              image:
                name: nkp-rocky-9.4-release-1.29.9-20241008013213.qcow2
                type: name
              memorySize: 16Gi
              subnets:
              - name: primary
                type: name
              systemDiskSize: 80Gi
              vcpuSockets: 4
              vcpusPerSocket: 1
        dns:
          coreDNS: {}
        encryptionAtRest:
          providers:
          - secretbox: {}
        globalImageRegistryMirror:
          url: http://registry.nutanixdemo.com/docker.io
        nutanix:
          controlPlaneEndpoint:
            host: 10.38.1.17
            port: 6443
            virtualIP:
              provider: KubeVIP
          prismCentralEndpoint:
            credentials:
              secretRef:
                name: cluster-2-pc-credentials
            insecure: true
            url: https://10.38.1.10:9440
    version: v1.29.9
    workers:
      machineDeployments:
      - class: default-worker
        metadata:
          annotations:
            cluster.x-k8s.io/cluster-api-autoscaler-node-group-max-size: "2"
            cluster.x-k8s.io/cluster-api-autoscaler-node-group-min-size: "2"
        name: md-0
        variables:
          overrides:
          - name: workerConfig
            value:
              nutanix:
                machineDetails:
                  bootType: uefi
                  cluster:
                    name: PHX-SPOC001-1
                    type: name
                  image:
                    name: nkp-rocky-9.4-release-1.29.9-20241008013213.qcow2
                    type: name
                  memorySize: 32Gi
                  subnets:
                  - name: primary
                    type: name
                  systemDiskSize: 80Gi
                  vcpuSockets: 8
                  vcpusPerSocket: 1
---
apiVersion: v1
data:
  credentials: WwogICAgewogICAgICAgICJ0eXBlIjogImJhc2ljX2F1dGgiLAogICAgICAgICJkYXRhIjogewogICAgICAgICAgICAicHJpc21DZW50cmFsIjogewogICAgICAgICAgICAgICAgInVzZXJuYW1lIjogImFkbWluIiwKICAgICAgICAgICAgICAgICJwYXNzd29yZCI6ICJueDJUZWNoNjcyISIKICAgICAgICAgICAgfQogICAgICAgIH0KICAgIH0KXQ==
kind: Secret
metadata:
  labels:
    cluster.x-k8s.io/provider: nutanix
    konvoy.d2iq.io/cluster-name: cluster-2
    konvoy.d2iq.io/provider: nutanix
  name: cluster-2-pc-credentials
  namespace: nav-workspace-8rnws
type: Opaque
---
apiVersion: v1
data:
  key: MTAuMzguMS4xMDo5NDQwOmFkbWluOm54MlRlY2g2NzIh
kind: Secret
metadata:
  labels:
    cluster.x-k8s.io/provider: nutanix
    konvoy.d2iq.io/cluster-name: cluster-2
    konvoy.d2iq.io/provider: nutanix
  name: cluster-2-pc-credentials-for-csi
  namespace: nav-workspace-8rnws
type: Opaque